version: '3.7'

services:
  nginx:
    env_file: .env
    build: 
      context: .
      dockerfile: ./compose/local/nginx.Dockerfile
    restart: always
    ports:
      - "${EX_PORT_NGINX:-8030}:80"
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
  core:
    env_file: .env
    build: 
      context: .
      dockerfile: ./compose/local/core.Dockerfile
      args:
        MYSQL_SERVER: ${MYSQL_SERVER:-}
        POSTGRES_SERVER: ${POSTGRES_SERVER:-}
    restart: always
    depends_on:
      - db
    volumes:
      - ./src:/home/app/web/
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
  db:
    env_file: .env
    build: 
      context: .
      dockerfile: ./compose/local/mysql.Dockerfile
      args:
        MYSQL_USER: ${MYSQL_USER:-}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DB:-}
    restart: always
    ports:
      - "3306:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
